name: gaussian_splatting
channels:
  - nvidia/label/cuda-11.6.2
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - cuda-toolkit=11.6
  - plyfile
  - python=3.7.13
  - pip=22.3.1
  - pytorch-gpu=1.12.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib
